FROM python:3.11

COPY ./frontend/requirements.txt  ./requirements.txt

RUN pip install -r requirements.txt

COPY ./frontend /frontend

# CMD ["tail", "-f", "/dev/null"]
CMD ["streamlit", "run", "frontend/assistant.py", "--theme.base=dark"]
